version: '3.9'
services:
  app:
    build:
      context: .
    container_name: messaging
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_USER}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASS}
      - RABBITMQ_EXCHANGE_NAME=messages_exchange
          
  db:
    image: 'postgres:14.2-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          
  rabbitmq:
    build:
      context: ./rabbit_mq/
    container_name: rabbitmq
    ports:
      - "15672:15672"
